spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: a5733ed3b55d8ad2a9be
            clientSecret: 46083f22032bad8f47b0ee92983e5fa1e55ad72f
            scope:
              - user:email
              - read:user
          google:
            clientId: 808525726674-m23lisgq4pr9q745bhftvrb2qqcrmm9o.apps.googleusercontent.com
            clientSecret: fv4nXI9xxiaiypHV6DKACypZ
            scope:
              - email
              - profile
          facebook:
            clientId: 659572495004882
            clientSecret: 06843ccaf91c22f86cb1e865ed12df27
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: secret
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris: http://localhost:4200/oauth2/redirect