spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
    clean-on-validation-error: true

  datasource:
    url: jdbc:postgresql://localhost:5432/flyway-demo-db?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: postgres
    password: postgres

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    root: debug

server:
  port: 0